version: 2.1

executors:
  my-executor:
    environment:
      TARGET_REPO: circleci-test
      A_REPO: repoA
      B_REPO: repoB

orbs:
  github-cli: circleci/github-cli@2.2.0

jobs:
  trigger_release:
    executor: my-executor
    machine: true
    steps:
      - github-cli/setup
      - run:
          name: Get repoA Release Version
          command: |
            echo "export A_RELEASE_VERSION=$(gh api repos/${CIRCLE_PROJECT_USERNAME}/${A_REPO}/releases/latest --jq '.tag_name' | sed 's/^v//')" >> "$BASH_ENV"
      - run:
          name: Get repoB Release Version
          command: |
            echo "export B_RELEASE_VERSION=$(gh api repos/${CIRCLE_PROJECT_USERNAME}/${B_REPO}/releases/latest --jq '.tag_name' | sed 's/^v//')" >> "$BASH_ENV"
      - run:
          name: Setup Environment Variables (Tag name)
          command: |
            echo "export TAG_NAME=py3.7-torch1.12-cuda11.3-cudnn8-${A_REPO}${A_RELEASE_VERSION}-${B_REPO}${B_RELEASE_VERSION}" >> "$BASH_ENV"
      - run:
          name: Print Environment Variables
          command: |
            echo "A_RELEASE_VERSION: ${A_RELEASE_VERSION}"
            echo "B_RELEASE_VERSION: ${B_RELEASE_VERSION}"
            echo "TAG_NAME: ${TAG_NAME}"
            source $BASH_ENV
      - run:
          name: Trigger release
          command: |
            gh api repos/${CIRCLE_PROJECT_USERNAME}/${TARGET_REPO}/releases \
              -X POST \
              -f tag_name=${TAG_NAME} \
              -f name=${TAG_NAME} \
              -f target_commitish='main' \
              -F body="Release ${TAG_NAME} from ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}" \
              -F draft=false \
              -F prerelease=false

workflows:
  release-flow:
    jobs:
      - trigger_release:
          context: default
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/